"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import {
  Accessibility,
  Activity,
  Baby,
  BicepsFlexed,
  Bone,
  BoneFracture,
  Dumbbell,
  HeartHandshake,
  HeartPulse,
  Home,
  CalendarPlus,
  MapPin,
  MonitorCheck,
  Newspaper,
  PersonStanding,
  Stethoscope,
  type LucideIcon,
} from "lucide-react";

type PageName = "home" | "about" | "services" | "divisions" | "team" | "patient" | "articles" | "contact" | "appointment" | "notfound";

const nav = [
  ["Home", "/"], ["About Us", "/about"], ["Services", "/services"], ["Divisions", "/divisions"],
  ["Our Team", "/team"], ["Patient Information", "/patient-information"], ["Articles", "/articles"], ["Contact", "/contact"],
];

const services = [
  ["MS", "Musculoskeletal Physiotherapy", "Assessment and rehabilitation for joint, muscle and movement problems.", "People living with pain, stiffness or reduced mobility.", "Joint pain, sprains, strains, posture-related pain"],
  ["SR", "Sports Injury Rehabilitation", "Structured recovery that supports a safe, confident return to sport.", "Recreational and competitive athletes.", "Sports injuries, overuse problems, reduced performance"],
  ["SP", "Spine and Back Pain Care", "Individual care for back, neck and spine-related symptoms.", "People with new or persistent spinal pain.", "Back pain, neck pain, sciatica, posture problems"],
  ["PS", "Post-Surgical Rehabilitation", "Progressive rehabilitation after surgery, guided by your clinical needs.", "People recovering from musculoskeletal surgery.", "Weakness, stiffness, reduced function after surgery"],
  ["NR", "Neurological Rehabilitation", "Movement-focused support for neurological conditions.", "People managing neurological movement challenges.", "Balance, mobility and functional movement limitations"],
  ["PD", "Paediatric Physiotherapy", "Age-appropriate assessment and movement support for children.", "Children and families seeking physiotherapy support.", "Movement, mobility and developmental concerns"],
  ["PM", "Pain Management", "Measured programmes that build confidence, movement and day-to-day function.", "People with persistent or recurring pain.", "Chronic pain, activity-related pain, movement sensitivity"],
  ["WE", "Workplace Ergonomics", "Practical assessment and training for healthier work environments.", "Teams and individuals in office or operational settings.", "Workstation strain, poor posture, repetitive load"],
  ["CW", "Corporate Wellness", "Workplace programmes that help prevent injury and support employee wellbeing.", "Companies and organisations across Uganda.", "Workplace screening, injury prevention, employee wellness"],
  ["AP", "Athlete Performance Support", "Movement, strength and return-to-performance support.", "Athletes building resilience and performance.", "Return to sport, injury prevention, performance limitations"],
];

const divisions = [
  ["Corporate", "CoreWell Corporate", "Workplace wellness built around healthier people and stronger organisations.", ["Workplace assessments", "Ergonomic training", "Employee wellness programmes", "Injury prevention", "Corporate screening", "Workplace rehabilitation"]],
  ["Spine", "CoreWell Spine Clinic", "Focused care for back, neck and spine-related conditions.", ["Back pain", "Neck pain", "Sciatica", "Disc-related conditions", "Posture problems", "Chronic spinal pain"]],
  ["Performance", "CoreWell Performance", "Sports rehabilitation and performance support from assessment to return to sport.", ["Sports injury assessment", "Rehabilitation", "Return-to-sport programmes", "Strength and conditioning support", "Injury prevention", "Athlete performance optimisation"]],
];

export const articles = [
  { slug: "manage-back-pain-at-work", category: "Workplace Health", title: "How to Manage Back Pain at Work", excerpt: "Simple, practical ways to reduce strain and move more comfortably through your workday.", date: "10 July 2026", time: "5 min read", image: "/images/articles/back-pain-at-work.jpg", imageAlt: "A physiotherapist helping an office worker adjust his chair and sitting posture", content: [
    "Back pain at work is common, but it does not always mean that the spine has been damaged. Symptoms can be influenced by how long you remain in one position, the amount of lifting or repeated movement in your day, recent changes in activity, sleep, stress and your general health. Understanding the pattern of your symptoms is often more useful than searching for one perfect posture.",
    "The body usually responds well to variety. If your work involves sitting, change your position regularly and stand or walk for a short time when you can. If your work is physical, alternating demanding tasks with lighter duties may reduce repeated strain. Small movement breaks throughout the day are often easier to maintain than waiting for one long break.",
    "A comfortable workstation should support the way you actually work. Keep frequently used items within easy reach, place the screen where you can view it without repeatedly twisting, and adjust the chair so your feet and arms feel supported. These changes are meant to make movement easier, not to hold you in one rigid position all day.",
    "Staying active is an important part of recovery for many people with uncomplicated back pain. Walking, gentle exercise and a gradual return to usual activity can help rebuild confidence and capacity. The right amount is individual, so increase activity progressively and pay attention to how your symptoms settle afterwards.",
    "Consider a physiotherapy assessment when pain is persistent, keeps returning, follows an injury or begins to interfere with sleep, work or normal movement. Your physiotherapist can assess the movements and work demands linked to your symptoms, explain the findings and develop a practical plan around your responsibilities and goals.",
    "Seek urgent medical attention if back pain follows major trauma or is accompanied by new or worsening weakness, loss of bladder or bowel control, numbness around the saddle area, chest pain, fever or unexplained illness. These symptoms need medical assessment rather than workplace advice alone."
  ] },
  { slug: "recovering-safely-sports-injury", category: "Sports", title: "Recovering Safely from a Sports Injury", excerpt: "Why a measured return-to-sport plan matters for confidence, capacity and performance.", date: "2 July 2026", time: "6 min read", image: "/images/articles/sports-injury-recovery.jpg", imageAlt: "An athlete completing a controlled rehabilitation exercise with a physiotherapist", content: [
    "A sports injury can affect more than the painful area. Time away from training may change strength, movement control, fitness and confidence, while the athlete may also feel pressure to return quickly. Good rehabilitation considers the whole person and the demands of the sport, not only whether pain has reduced.",
    "The first step is a clear assessment. A physiotherapist will ask how the injury happened, examine movement and function, and consider any previous injuries or training changes. This helps identify what is safe to begin now and what needs to be rebuilt before higher-level activity is introduced.",
    "Rehabilitation usually progresses from restoring comfortable movement to developing strength, balance, control and the ability to tolerate repeated load. Progress is guided by how the body responds rather than by the calendar alone. Some discomfort may occur during recovery, but symptoms should be monitored and the programme adjusted when the response is excessive or does not settle as expected.",
    "As capacity improves, exercises should begin to resemble the real demands of the athlete's sport. Running, jumping, landing, changing direction or handling contact may need to be reintroduced in stages. Training in a controlled environment allows the athlete and clinician to observe movement quality before intensity and unpredictability increase.",
    "Confidence is part of recovery. An athlete may be physically stronger but still hesitate during a movement associated with the injury. Practising sport-specific tasks, reviewing progress and understanding why each stage is included can help rebuild trust in the body without rushing the process.",
    "Return to sport is best treated as a progression from rehabilitation to modified training and then full participation. Decisions should reflect symptoms, function, sport-specific testing, training response and the athlete's own confidence, with clear communication between the athlete, physiotherapist and coaching team."
  ] },
  { slug: "when-to-see-physiotherapist", category: "Patient Guide", title: "When Should You See a Physiotherapist?", excerpt: "A clear guide to symptoms, movement problems and recovery concerns that deserve attention.", date: "24 June 2026", time: "4 min read", image: "/images/articles/physiotherapy-consultation.jpg", imageAlt: "A physiotherapist having a calm first consultation with a patient", content: [
    "Physiotherapy may be helpful when pain, stiffness, weakness or reduced movement is making daily life more difficult. You do not need to wait until a problem becomes severe. An assessment can be useful when symptoms persist, keep returning or begin to limit work, exercise, sleep or the activities that matter to you.",
    "People also seek physiotherapy after a sprain, strain, fracture, operation or period of illness that has reduced their function. Rehabilitation can support a gradual return to walking, lifting, work, recreation or sport by matching activity to the person's current capacity and recovery goals.",
    "At the first visit, the physiotherapist will listen to your history and ask about your symptoms, health, lifestyle and priorities. The physical assessment may look at movement, strength, balance and the tasks you are finding difficult. You should receive a clear explanation of the findings and have the opportunity to ask questions.",
    "Treatment is not the same for every person. Depending on the assessment, your plan may include education, movement practice, progressive exercise, changes to daily activities and strategies for managing symptoms. The aim is to help you understand the problem and build the confidence and ability to manage it beyond the clinic.",
    "An early conversation can also be valuable when you are unsure whether physiotherapy is appropriate. A licensed physiotherapist can recognise when a musculoskeletal problem is suitable for physiotherapy and when further medical review or another service may be needed.",
    "Urgent symptoms should not wait for a routine physiotherapy appointment. Seek prompt medical care after major trauma, for sudden or progressive weakness, chest pain, difficulty breathing, loss of bladder or bowel control, severe unexplained illness or any rapidly worsening concern."
  ] },
  { slug: "understanding-neck-pain", category: "Spine Health", title: "Understanding Neck Pain", excerpt: "Common contributors to neck discomfort and when an assessment may help.", date: "16 June 2026", time: "5 min read", image: "/images/articles/neck-pain-assessment.jpg", imageAlt: "A physiotherapist carefully assessing a patient's neck movement", content: [
    "Neck pain can begin after an injury, a change in activity or a long period spent in one position, but it can also develop without one obvious cause. The neck is a strong and mobile area, and many episodes improve with time, comfortable movement and a gradual return to normal activity.",
    "Symptoms may be influenced by several factors at once. Work demands, sleep, stress, physical activity and how confident you feel moving the neck can all shape the experience of pain. This is why two people with similar symptoms may need different advice and rehabilitation plans.",
    "There is rarely one perfect posture that must be maintained throughout the day. A more practical approach is to use comfortable positions, change them regularly and avoid holding the neck still for long periods. Gentle movement within a tolerable range can help maintain confidence and reduce stiffness.",
    "Daily habits can support recovery. Arrange work so you do not repeatedly turn toward one side, take short breaks from sustained screen use and choose a sleeping position that feels comfortable. Exercise should be introduced gradually, with the amount and direction guided by your symptoms and assessment.",
    "A physiotherapy assessment may help when pain lasts for several weeks, keeps returning, follows an injury or is accompanied by arm symptoms. The physiotherapist can examine neck and shoulder movement, strength and relevant nerve function, then explain the findings and agree on a plan suited to your needs.",
    "Seek urgent medical care for neck pain after major trauma or when it occurs with severe headache, fever, unexplained illness, new problems with balance, vision, speech or swallowing, or progressive weakness or numbness. These features require medical assessment rather than self-management alone."
  ] },
  { slug: "workplace-ergonomics-matters", category: "Corporate Wellness", title: "Why Workplace Ergonomics Matters", excerpt: "How work design can support comfort, productivity and injury prevention.", date: "8 June 2026", time: "5 min read", image: "/images/articles/workplace-ergonomics.jpg", imageAlt: "A workplace physiotherapist reviewing a computer workstation with an employee", content: [
    "Ergonomics is the practical process of fitting work to people. It looks beyond the chair or desk and considers the task, tools, environment, workload and way the job is organised. The goal is to create work that can be performed comfortably, safely and efficiently by the people doing it.",
    "A workstation assessment should reflect the individual and the work being completed. Screen height, keyboard position, seating, lighting and the location of frequently used items can all affect comfort. Adjustments should make it easier to move and work naturally rather than forcing the body into one fixed posture.",
    "Movement variety matters in both office and physical roles. Long periods of static work, repeated reaching or lifting, and tasks performed at an unsuitable height can become tiring over time. Alternating tasks, planning sensible recovery periods and allowing workers to change position can reduce unnecessary strain.",
    "Ergonomics is most effective when employees are involved. Workers understand the practical demands and obstacles in their roles, while managers can help address equipment, workflow and scheduling. A solution that looks ideal on paper will not help if it is difficult to use during a normal working day.",
    "Early attention to discomfort can prevent a manageable concern from becoming a larger barrier to work. Employees should feel able to report symptoms, request reasonable adjustments and seek professional advice. Physiotherapy can help identify the relationship between a person's symptoms, capacity and work demands.",
    "A strong workplace programme combines assessment with education, movement and ongoing review. As roles, teams and equipment change, the working environment may need to change too. The result is not only better comfort, but a workplace culture that values health, participation and sustainable performance."
  ] },
  { slug: "returning-to-sport-after-injury", category: "Performance", title: "Returning to Sport After Injury", excerpt: "What a progressive return looks like and why testing readiness matters.", date: "30 May 2026", time: "6 min read", image: "/images/articles/return-to-sport.jpg", imageAlt: "A runner completing a return-to-sport drill while a physiotherapist observes", content: [
    "Returning to sport is not a single moment at the end of rehabilitation. It is a progression that begins when an athlete starts rebuilding movement and continues through modified training, full training and confident participation. Each stage gives useful information about how the body responds to greater demand.",
    "The early foundation usually includes comfortable movement, strength and control. From there, rehabilitation should rebuild the qualities required by the athlete's activity, such as endurance, speed, power, balance or repeated effort. The programme should reflect the position, event and level of competition rather than use the same plan for every athlete.",
    "Training load needs to increase gradually. A movement that feels comfortable once may still be difficult when it is repeated, performed quickly or completed under fatigue. Monitoring symptoms during the session and over the following day helps the physiotherapist decide whether to maintain, progress or modify the programme.",
    "Sport-specific testing can reveal gaps that are not obvious during basic exercise. Running, landing, changing direction, jumping or contact preparation may be assessed according to the sport. Test results are most useful when combined with clinical findings and the athlete's actual response to training.",
    "Psychological readiness matters as well. Fear of another injury can change how an athlete moves and makes decisions, even when physical measures have improved. Gradual exposure to challenging tasks and honest discussion about confidence can support a more complete return.",
    "The final decision should be shared and individual. Symptoms, function, training response, testing, confidence and the risks of the sport all contribute to readiness. A careful return may take patience, but it gives the athlete a stronger foundation for performance and continued participation."
  ] },
];

function Brand() { return <Link className="brand" href="/" aria-label="CoreWell Uganda home"><img className="brand-logo" src="/images/corewell-logo.png" alt="" /><span><b>CoreWell</b><small>Physiotherapy &amp; Musculoskeletal Health</small></span></Link>; }

function Header() {
  const [open, setOpen] = useState(false);
  return <>
    <div className="topbar"><div className="container topbar-inner"><span>People&apos;s Medical Hospital, Gayaza, Kampala</span><span><a href="tel:+256761393569">+256 761 393 569</a><i /> <a href="mailto:info@corewellmusculoskeletaluganda.com">info@corewellmusculoskeletaluganda.com</a></span></div></div>
    <header className="header"><div className="container navrow"><Brand/><button className="menubtn" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation"><span/><span/><span/></button><nav className={open ? "nav open" : "nav"}>{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link className="btn btn-small" href="/appointment" onClick={() => setOpen(false)}>Book Appointment</Link></nav></div></header>
    <nav className="mobile-dock" aria-label="Mobile quick navigation">
      <Link href="/"><Home aria-hidden="true"/><span>Home</span></Link>
      <Link href="/services"><Stethoscope aria-hidden="true"/><span>Services</span></Link>
      <Link className="dock-book" href="/appointment"><CalendarPlus aria-hidden="true"/><span>Book</span></Link>
      <Link href="/articles"><Newspaper aria-hidden="true"/><span>Articles</span></Link>
      <Link href="/contact"><MapPin aria-hidden="true"/><span>Contact</span></Link>
    </nav>
  </>;
}

function Footer() { return <footer><div className="container footergrid"><div><Brand/><p>Licensed physiotherapy and musculoskeletal health services for individuals, organisations and athletes across Uganda.</p></div><div><h4>Quick links</h4>{nav.slice(1,5).map(([l,h]) => <Link key={h} href={h}>{l}</Link>)}</div><div><h4>Our divisions</h4><Link href="/divisions">CoreWell Corporate</Link><Link href="/divisions">CoreWell Spine Clinic</Link><Link href="/divisions">CoreWell Performance</Link></div><div><h4>Contact</h4><p>People&apos;s Medical Hospital<br/>Gayaza, Kampala, Uganda</p><a href="tel:+256761393569">+256 761 393 569</a><a href="mailto:info@corewellmusculoskeletaluganda.com">info@corewellmusculoskeletaluganda.com</a></div></div><div className="container footnote"><span>© 2026 CoreWell Uganda Limited. All rights reserved.</span><span><a href="#">Privacy Policy</a><a href="#">Terms &amp; Conditions</a></span></div></footer>; }

function SectionHead({ eyebrow, title, copy, center=false }: { eyebrow:string; title:string; copy?:string; center?:boolean }) { return <div className={center ? "sectionhead center" : "sectionhead"}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }

function Hero() { return <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Physiotherapy &amp; Musculoskeletal Health</span><h1>Expert Physiotherapy.<br/><em>Stronger You.</em></h1><p className="lead">CoreWell Uganda provides evidence-based care for pain relief, injury recovery, spine health and lifelong movement.</p><div className="actions"><Link className="btn" href="/appointment">Book an Appointment</Link><Link className="btn btn-ghost" href="/services">Our Services</Link></div><div className="trust"><span>Licensed Professionals</span><span>Evidence-Based Care</span><span>Patient-Centred Treatment</span></div></div><div className="hero-visual"><div className="imageframe"><img src="/images/hero-physio.png" alt="Physiotherapist guiding a patient through a shoulder mobility exercise"/></div><div className="floatcard"><b>A Uganda that moves without pain.</b><span>Care built around your goals.</span></div></div></div></section>; }

const serviceIcons: Record<string, LucideIcon> = {
  "Musculoskeletal Physiotherapy": BicepsFlexed,
  "Sports Injury Rehabilitation": Accessibility,
  "Spine and Back Pain Care": Bone,
  "Post-Surgical Rehabilitation": BoneFracture,
  "Neurological Rehabilitation": PersonStanding,
  "Paediatric Physiotherapy": Baby,
  "Pain Management": HeartPulse,
  "Workplace Ergonomics": MonitorCheck,
  "Corporate Wellness": HeartHandshake,
  "Athlete Performance Support": Dumbbell,
};

function ServiceIcon({ title }: { title: string }) {
  const Icon = serviceIcons[title] ?? Activity;
  return <Icon aria-hidden="true" size={27} strokeWidth={1.75} />;
}

function ServiceGrid({ full=false }: { full?:boolean }) { const list = full ? services : services.slice(0,6); return <div className={full ? "servicegrid full" : "servicegrid"}>{list.map(([,title,desc,who,conditions]) => <article className="servicecard" key={title as string}><span className="lineicon"><ServiceIcon title={title as string}/></span><h3>{title as string}</h3><p>{desc as string}</p>{full && <><div className="service-meta"><b>Who it is for</b><span>{who as string}</span></div><div className="service-meta"><b>Common concerns</b><span>{conditions as string}</span></div><Link className="textlink" href="/appointment">Book Appointment <span>→</span></Link></>}</article>)}</div>; }

function DivisionGrid({ detailed=false }: { detailed?:boolean }) { return <div className="divisiongrid">{divisions.map(([tag,title,desc,items]) => <article className="divisioncard" key={title as string}><span className="divisiontag">{tag as string}</span><h3>{title as string}</h3><p>{desc as string}</p>{detailed && <ul>{(items as string[]).map(i => <li key={i}>{i}</li>)}</ul>}<Link className="textlink" href={detailed ? "/appointment" : "/divisions"}>{detailed ? "Book an appointment" : "Learn more"} <span>→</span></Link></article>)}</div>; }

function TeamCards({ full=false }: {full?:boolean}) { const team = [["JK","Julius Kaweesa","+256 761 393 569","julius@corewellmusculoskeletaluganda.com"],["KE","Kajwiga Emmanuel","+256 784 106 753","emma@corewellmusculoskeletaluganda.com"]]; return <div className="teamgrid">{team.map(([initials,name,phone,email]) => <article className="teamcard" key={name}><div className="portrait"><span>{initials}</span></div><div className="teamcopy"><span className="license">Licensed Physiotherapist</span><h3>{name}</h3><p>Co-Founder</p>{full ? <div className="teamcontact"><a href={`tel:${phone.replace(/\s/g,"")}`}>{phone}</a><a href={`mailto:${email}`}>{email}</a></div> : <Link className="textlink" href="/team">View profile <span>→</span></Link>}</div></article>)}</div>; }

function ArticleCards({ limit=6 }: {limit?:number}) { return <div className="articlegrid">{articles.slice(0,limit).map(a => <article className="articlecard" key={a.slug}><div className="articlevisual"><img src={a.image} alt={a.imageAlt}/><span>{a.category}</span></div><div className="articlebody"><span className="articlemeta">{a.date} · {a.time}</span><h3>{a.title}</h3><p>{a.excerpt}</p><Link className="textlink" href={`/articles/${a.slug}`}>Read article <span>→</span></Link></div></article>)}</div>; }

function ContactForm({ appointment=false }: {appointment?:boolean}) { const [sent,setSent] = useState(false); function submit(e:FormEvent){e.preventDefault();setSent(true);} return <form className="form" onSubmit={submit}>{sent ? <div className="success"><b>Thank you.</b><p>Your request has been recorded on this device. Please call us if you need a faster response.</p><button className="btn" type="button" onClick={()=>setSent(false)}>Send another request</button></div> : <>{appointment ? <><label>Full name<input required name="name"/></label><div className="formrow"><label>Phone number<input required type="tel"/></label><label>Email<input required type="email"/></label></div><div className="formrow"><label>Preferred service<select required><option value="">Choose a service</option>{services.map(s=><option key={s[1]}>{s[1]}</option>)}</select></label><label>Patient type<select required><option>Individual</option><option>Corporate</option><option>Athlete</option></select></label></div><div className="formrow"><label>Preferred date<input required type="date"/></label><label>Preferred time<input required type="time"/></label></div><label>Brief description of the problem<textarea required rows={5}/></label><label className="consent"><input required type="checkbox"/> I consent to CoreWell Uganda contacting me about this appointment request.</label></> : <><div className="formrow"><label>Full name<input required/></label><label>Phone number<input required type="tel"/></label></div><label>Email<input required type="email"/></label><label>Service needed<select required><option value="">Select a service</option>{services.map(s=><option key={s[1]}>{s[1]}</option>)}</select></label><label>Message<textarea required rows={4}/></label></>}<button className="btn" type="submit">{appointment ? "Request Appointment" : "Send Message"}</button></>}</form>; }

function PageHero({ eyebrow, title, copy }: {eyebrow:string;title:string;copy:string}) { return <section className="pagehero"><div className="container narrow"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div></section>; }

function HomePage(){ return <><Hero/><section className="section aboutpreview"><div className="container twocol"><div className="aboutart"><div className="aboutbadge">Clinical excellence<br/><b>Measured outcomes</b></div></div><div><SectionHead eyebrow="About CoreWell" title="Care that helps Uganda move well" copy="CoreWell Uganda Limited is a licensed physiotherapy company founded by two physiotherapists, Julius Kaweesa and Kajwiga Emmanuel. We serve individuals, organisations and athletes across Uganda."/><div className="valuegrid"><div><b>Our vision</b><span>A Uganda that moves without pain.</span></div><div><b>Our mission</b><span>To prevent, treat and rehabilitate musculoskeletal conditions with clinical excellence.</span></div></div><Link className="btn btn-ghost" href="/about">Learn More About CoreWell</Link></div></div></section><section className="section"><div className="container"><SectionHead center eyebrow="Our Services" title="Specialist care for every stage of movement" copy="Evidence-based programmes delivered exclusively by licensed physiotherapists."/><ServiceGrid/><div className="center actionbelow"><Link className="btn btn-ghost" href="/services">View All Services</Link></div></div></section><section className="section pale"><div className="container"><SectionHead eyebrow="Three focused divisions" title="One connected standard of care"/><DivisionGrid/></div></section><section className="section"><div className="container"><SectionHead eyebrow="Our founders" title="Licensed professionals, personally invested"/><TeamCards/></div></section><section className="quote-strip"><div className="container quotegrid"><blockquote>“Our goal is not only to reduce pain. It is to help each person return to the movement, work and sport that matters to them.”<cite>CoreWell Uganda clinical approach</cite></blockquote><div className="stat"><b>Licensed</b><span>physiotherapists only</span></div><div className="stat"><b>3</b><span>specialist divisions</span></div><div className="stat"><b>1</b><span>patient-centred plan</span></div></div></section><section className="section pale"><div className="container"><SectionHead center eyebrow="Patient information" title="Know what to expect"/><div className="infogrid"><article><span>01</span><h3>Who we serve</h3><p>Individuals, organisations and athletes seeking evidence-based physiotherapy support.</p></article><article><span>02</span><h3>What to expect</h3><p>A clear assessment, explanation of findings and a treatment plan built around your goals.</p></article><article><span>03</span><h3>Our care approach</h3><p>Outcomes-measured programmes delivered by licensed physiotherapists.</p></article></div></div></section><section className="section"><div className="container"><SectionHead eyebrow="Health insights" title="Latest from CoreWell"/><ArticleCards limit={3}/></div></section><ContactSection/></>; }

function ContactSection(){ return <section className="section contactsection"><div className="container contactgrid"><div className="contactintro"><SectionHead eyebrow="Contact us" title="Start moving toward better health" copy="Visit us in Gayaza, call our team or send a message."/><div className="contactlist"><p><b>Clinic</b>People&apos;s Medical Hospital<br/>Gayaza, Kampala, Uganda</p><p><b>Phone</b><a href="tel:+256761393569">+256 761 393 569</a><a href="tel:+256784106753">+256 784 106 753</a></p><p><b>Email</b><a href="mailto:info@corewellmusculoskeletaluganda.com">info@corewellmusculoskeletaluganda.com</a></p></div></div><ContactForm/><iframe className="map" title="Map showing People's Medical Hospital in Gayaza" loading="lazy" src="https://www.google.com/maps?q=People%27s%20Medical%20Hospital%20Gayaza%20Kampala%20Uganda&output=embed"/></div></section>; }

function AboutPage(){return <><PageHero eyebrow="About CoreWell Uganda" title="Clinical excellence, one patient and one organisation at a time." copy="A licensed physiotherapy company helping people across Uganda prevent, treat and rehabilitate musculoskeletal conditions."/><section className="section"><div className="container twocol"><div><SectionHead eyebrow="Our story" title="Founded by physiotherapists" copy="CoreWell Uganda Limited was founded by Julius Kaweesa and Kajwiga Emmanuel. The company provides clinical musculoskeletal health services to individuals, organisations and athletes across Uganda."/><p>Our approach is evidence-based and outcomes-measured. Every programme is delivered exclusively by licensed physiotherapists.</p></div><div className="principles"><article><span>01</span><h3>Vision</h3><p>A Uganda that moves without pain.</p></article><article><span>02</span><h3>Mission</h3><p>To prevent, treat and rehabilitate musculoskeletal conditions with clinical excellence, one patient and one organisation at a time.</p></article><article><span>03</span><h3>Clinical approach</h3><p>Evidence-based, outcomes-measured programmes delivered exclusively by licensed physiotherapists.</p></article></div></div></section><section className="section pale"><div className="container"><SectionHead center eyebrow="How we work" title="Clear care. Measured progress."/><div className="infogrid"><article><span>01</span><h3>Listen</h3><p>We begin with your history, concerns and goals.</p></article><article><span>02</span><h3>Assess</h3><p>We examine movement and the factors relevant to your condition.</p></article><article><span>03</span><h3>Plan</h3><p>We explain our findings and agree on a practical treatment plan.</p></article></div></div></section></>}

function ServicesPage(){return <><PageHero eyebrow="Our services" title="Physiotherapy built around real life." copy="Detailed assessment and rehabilitation for pain, injury, recovery, work and performance."/><section className="section"><div className="container"><ServiceGrid full/></div></section><CTA/></>}
function DivisionsPage(){return <><PageHero eyebrow="CoreWell divisions" title="Focused expertise for work, spine health and performance." copy="Three specialist divisions, united by one evidence-based standard of care."/><section className="section"><div className="container"><DivisionGrid detailed/></div></section><CTA/></>}
function TeamPage(){return <><PageHero eyebrow="Our team" title="Care delivered by licensed physiotherapists." copy="Meet the co-founders of CoreWell Uganda Limited."/><section className="section"><div className="container"><TeamCards full/><p className="accuracy-note">CoreWell does not publish unverified qualifications, awards or experience claims. Contact the clinic directly if you would like to learn more about your treating physiotherapist.</p></div></section></>}
function PatientPage(){const steps=[["Before your visit","Bring relevant medical reports, imaging, referral notes and a list of current medicines if available."],["Suitable clothing","Wear comfortable clothing that allows the area being assessed to move freely."],["Assessment","Your physiotherapist will discuss your symptoms and goals, then assess movement, strength and function."],["Treatment planning","Findings will be explained clearly and a plan will be agreed with you."],["Follow-up sessions","Progress will be reviewed and your programme adjusted according to your response and goals."]];return <><PageHero eyebrow="Patient information" title="Your first appointment, explained." copy="Simple guidance to help you arrive prepared and know what to expect."/><section className="section"><div className="container patientlayout"><div>{steps.map(([t,c],i)=><article className="step" key={t}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{t}</h3><p>{c}</p></div></article>)}</div><aside className="urgent"><h3>When to seek urgent medical attention</h3><p>Seek urgent care for severe symptoms after major trauma, sudden weakness, chest pain, difficulty breathing, loss of bladder or bowel control, or any rapidly worsening medical concern.</p><p>This website does not replace emergency medical advice.</p></aside></div></section><section className="section pale"><div className="container narrow"><SectionHead center eyebrow="Frequently asked questions" title="Before you visit"/><details><summary>Do I need a referral?</summary><p>Contact the clinic to discuss your situation and whether a referral or existing medical information would be helpful.</p></details><details><summary>How long will treatment take?</summary><p>The number and frequency of sessions depends on your assessment, goals and response to care. Your physiotherapist will discuss this with you.</p></details><details><summary>Can CoreWell support organisations and athletes?</summary><p>Yes. CoreWell Corporate supports workplaces and CoreWell Performance supports athletes and return-to-sport programmes.</p></details></div></section><CTA/></>}
function ArticlesPage(){return <><PageHero eyebrow="CoreWell articles" title="Practical guidance for healthier movement." copy="Clear, evidence-informed reading for patients, workplaces and athletes."/><section className="section"><div className="container"><ArticleCards/></div></section></>}
function ContactPage(){return <><PageHero eyebrow="Contact CoreWell" title="We are ready to listen." copy="Reach our team in Gayaza, Kampala, and take the next step toward moving well."/><ContactSection/></>}
function AppointmentPage(){return <><PageHero eyebrow="Book an appointment" title="Tell us how we can help." copy="Send an appointment request and the CoreWell team will contact you to confirm availability."/><section className="section"><div className="container appointmentgrid"><div><SectionHead eyebrow="Your visit" title="Personal care starts with a clear conversation." copy="Complete the form with your preferred time and service. This request does not confirm an appointment until our team contacts you."/><div className="contactpanel"><b>Prefer to call?</b><a href="tel:+256761393569">+256 761 393 569</a><a href="tel:+256784106753">+256 784 106 753</a></div></div><ContactForm appointment/></div></section></>}
function CTA(){return <section className="cta"><div className="container"><div><span className="eyebrow light">Ready to move forward?</span><h2>Start with a physiotherapy assessment.</h2></div><Link className="btn btn-white" href="/appointment">Book an Appointment</Link></div></section>}

export function SitePage({page}:{page:PageName}) { let content; switch(page){case "home":content=<HomePage/>;break;case "about":content=<AboutPage/>;break;case "services":content=<ServicesPage/>;break;case "divisions":content=<DivisionsPage/>;break;case "team":content=<TeamPage/>;break;case "patient":content=<PatientPage/>;break;case "articles":content=<ArticlesPage/>;break;case "contact":content=<ContactPage/>;break;case "appointment":content=<AppointmentPage/>;break;default:content=<><PageHero eyebrow="404" title="This page could not be found." copy="The page may have moved, or the address may be incorrect."/><div className="section center"><Link className="btn" href="/">Return Home</Link></div></>;} return <><Header/><main>{content}</main><Footer/></>; }

export function ArticlePage({slug}:{slug:string}) { const a=articles.find(x=>x.slug===slug); if(!a)return <SitePage page="notfound"/>; const related=articles.filter(x=>x.slug!==slug).slice(0,3); return <><Header/><main><article className="articlepage"><div className="container articlecopy"><Link className="backlink" href="/articles">← Back to Articles</Link><span className="eyebrow">{a.category}</span><h1>{a.title}</h1><p className="articledek">{a.excerpt}</p><div className="articlemeta">CoreWell Uganda · {a.date} · {a.time}</div><div className="articlelead"><img src={a.image} alt={a.imageAlt}/><span>{a.category}</span></div>{a.content.map((p,i)=><p key={i}>{p}</p>)}<div className="articlecallout"><b>Need a personal assessment?</b><p>Article information is general and cannot replace an individual clinical assessment.</p><Link className="btn" href="/appointment">Book an Appointment</Link></div></div></article><section className="section pale"><div className="container"><SectionHead eyebrow="Keep reading" title="Related articles"/><div className="articlegrid">{related.map(r=><article className="articlecard" key={r.slug}><div className="articlevisual"><img src={r.image} alt={r.imageAlt}/><span>{r.category}</span></div><div className="articlebody"><h3>{r.title}</h3><p>{r.excerpt}</p><Link className="textlink" href={`/articles/${r.slug}`}>Read article <span>→</span></Link></div></article>)}</div></div></section></main><Footer/></>; }
